[package]
name = "script"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
bitcrypto = { path = "../crypto" }
chain = { path = "../chain" }
keys = { path = "../keys" }
primitives = { path = "../primitives" }
serde = "1.0"
serialization = { path = "../serialization" }
log = "0.4"
blake2b_simd = "0.5"
cryptoconditions = { git = "https://github.com/alrighttt/cryptoconditions-js.git", commit = "6723ee2d" }
rustc-hex = "2.1.0"
libsecp256k1 = "0.6.0"
